name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: |
        dotnet build
    - name: Archive Build Output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: PlaywrightFirstDemo/PlaywrightDemo/bin/Debug/net8.0/
    - name: Ensure browsers are installed
      run: pwsh ./PlaywrightDemo/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      run: dotnet test --logger "trx;LogFileName=test_results.trx"
      continue-on-error: true  # Continue even if tests fail
    - name: Upload Test Results Artifact
      uses: actions/upload-artifact@v3
      with:
        name: playwright-traces
        path: PlaywrightFirstDemo/PlaywrightDemo/bin/Debug/net8.0/playwright-traces/*.zip  # Point to the .zip files
